import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/lib/auth/authConfig";
import { Session } from "next-auth";
import { QueryContextProvider } from "@/contexts/QueryContextProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import NavBar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await auth();
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* for proper layout add header, main and footer */}
        <header></header>
          <SessionProvider session={session}>
            <ThemeProvider enableSystem={false}>
              <QueryContextProvider>
                  <main>
                      <div className="flex h-full w-full gap-10">
                        <SidebarProvider>
                            <AppSidebar/>
                                <div>
                                    <SidebarTrigger />
                                </div>
                        </SidebarProvider>
                        <div id="mainContent" className="content w-full px-10">
                            <NavBar/>
                            {children}
                        </div>
                      </div>
                  </main>
                <ReactQueryDevtools initialIsOpen={false} />
              </QueryContextProvider>
            </ThemeProvider>
          </SessionProvider>
        <footer></footer>
      </body>
    </html>
  );
}